Repository inu-appcenter/server-study-15.5, pull requests merged in 2023-11, with the labels that each got.

#63 [Feat] - Controller & Service 구현 및 Swagger를 이용한 API 명세서 자동화 구현
  contents/concepts/week3/sy/3주차 발표자료.md
  contents/todoListAPI/sy/ToDoList/build.gradle
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Config/SwaggerConfig.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Controller/EmotionController.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Controller/ReplyController.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Controller/ToDoController.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Controller/UserController.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/Reply/AddReplyReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/Reply/ChangeReplyReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/Reply/ReadReplyResDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/ToDo/AddToDoReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/ToDo/ReadToDoPreviewResDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/ToDo/ReadToDoResDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/ToDo/UpdateToDoReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/User/AddUserReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/User/ChangeUserReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/User/DeleteUserReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/User/ReadUserResDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Repository/BoardRepository.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Repository/EmotionRepository.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Repository/ToDoRepository.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Repository/UserRepository.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Service/EmotionService.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Service/ReplyService.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Service/ToDoService.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Service/UserService.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/ToDoListApplication.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/BaseEntity.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/Emotion.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/Reply.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/ToDo.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/User.java
  contents/todoListAPI/sy/ToDoList/src/main/resources/application.properties
Labels: ✨ New Feature

#66 [Clean,Refactor] Controller & Service & Dto & Entity 수정
  contents/concepts/week4/hj/REST API d2b71522c4404668b8cf383bf60948c4.md
  contents/concepts/week4/hj/REST API d2b71522c4404668b8cf383bf60948c4/Untitled 1.png
  contents/concepts/week4/hj/REST API d2b71522c4404668b8cf383bf60948c4/Untitled 2.png
  contents/concepts/week4/hj/REST API d2b71522c4404668b8cf383bf60948c4/Untitled 3.png
  contents/concepts/week4/hj/REST API d2b71522c4404668b8cf383bf60948c4/Untitled 4.png
  contents/concepts/week4/hj/REST API d2b71522c4404668b8cf383bf60948c4/Untitled 5.png
  contents/concepts/week4/hj/REST API d2b71522c4404668b8cf383bf60948c4/Untitled 6.png
  contents/concepts/week4/hj/REST API d2b71522c4404668b8cf383bf60948c4/Untitled 7.png
  contents/concepts/week4/hj/REST API d2b71522c4404668b8cf383bf60948c4/Untitled 8.png
  contents/concepts/week4/hj/REST API d2b71522c4404668b8cf383bf60948c4/Untitled.png
  contents/todoListAPI/hj/MyTodoList/build.gradle
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/Repository/TodoRepository.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/config/SwaggerConfig.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/controller/TodoController.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/controller/UserController.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/domain/Time.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/domain/Todo.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/domain/User.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/dto/TodoRequestDto.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/dto/TodoResponseDto.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/dto/UserRequestDto.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/dto/UserResponseDto.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/service/TodoService.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/service/UserService.java
  contents/todoListAPI/hj/MyTodoList/src/main/resources/application.properties
  contents/todoListAPI/hj/MyTodoList/src/main/resources/application.yml
Labels: 🧹 Clean Up, ♻️ Refactoring

#52 [Docs]3주차 업로드(API)#49
  contents/concepts/week3/4주차.md
  contents/concepts/week3/Untitled 1.png
  contents/concepts/week3/Untitled 2.png
  contents/concepts/week3/Untitled 3.png
  contents/concepts/week3/Untitled 4.png
  contents/concepts/week3/Untitled 6.png
  contents/concepts/week3/Untitled 7.png
  contents/concepts/week3/Untitled 8.png
  contents/concepts/week3/Untitled 9.png
  contents/concepts/week3/Untitled.png
  contents/todoListAPI/ja/TodoProject/build.gradle
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/TodoProjectApplication.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/common/CommonResponse.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/config/GlobalExceptionHandler.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/config/SwaggerConfig.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/config/ex/DuplicatedException.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/config/ex/NotFoundException.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/controller/ClientController.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/controller/TodoController.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/controller/TodoGroupController.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/Client/ClientRequestDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/Client/ClientResponseDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/CommonResponseDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/RequestClientDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/RequestTodoDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/Todo/TodoRequestDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/Todo/TodoResponseDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/TodoGroup/TodoGroupRequestDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/TodoGroup/TodoGroupResponseDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/entity/Client.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/entity/Todo.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/entity/TodoGroup.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/repository/ClientRepository.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/repository/TodoGroupRepository.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/repository/TodoRepository.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/service/ClientService.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/service/TodoGroupService.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/service/TodoService.java
  contents/todoListAPI/ja/TodoProject/src/main/resources/application-dev.yml
Labels: 📘 Documentation, ✨ New Feature, ♻️ Refactoring

#76 [Feat,Refactor,Docs] 예외처리 ,로깅 및 유효성검사 구현,Service & Controller 코드 수정 &6주차 발표자료 업로드- #68, #70, #79
  contents/concepts/week6/hj/유효성 검사 ca6510890ca3485da79e634557e06999.md
  contents/concepts/week6/hj/유효성 검사 ca6510890ca3485da79e634557e06999/Untitled 1.png
  contents/concepts/week6/hj/유효성 검사 ca6510890ca3485da79e634557e06999/Untitled 2.png
  contents/concepts/week6/hj/유효성 검사 ca6510890ca3485da79e634557e06999/Untitled 3.png
  contents/concepts/week6/hj/유효성 검사 ca6510890ca3485da79e634557e06999/Untitled 4.png
  contents/concepts/week6/hj/유효성 검사 ca6510890ca3485da79e634557e06999/Untitled 5.png
  contents/concepts/week6/hj/유효성 검사 ca6510890ca3485da79e634557e06999/Untitled 6.png
  contents/concepts/week6/hj/유효성 검사 ca6510890ca3485da79e634557e06999/Untitled 7.png
  contents/concepts/week6/hj/유효성 검사 ca6510890ca3485da79e634557e06999/Untitled 8.png
  contents/concepts/week6/hj/유효성 검사 ca6510890ca3485da79e634557e06999/Untitled.png
  contents/todoListAPI/hj/MyTodoList/build.gradle
  contents/todoListAPI/hj/MyTodoList/logs/info_type_IS_UNDEFINED.2023-11-12.gz
  contents/todoListAPI/hj/MyTodoList/logs/info_type_IS_UNDEFINED.2023-11-14.gz
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/MyTodoListApplication.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/common/CustomExceptionHandler.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/controller/TodoController.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/controller/UserController.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/domain/Time.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/domain/Todo.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/domain/User.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/dto/TodoRequestDto.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/dto/TodoResponseDto.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/dto/UserRequestDto.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/dto/UserResponseDto.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/service/TodoService.java
  contents/todoListAPI/hj/MyTodoList/src/main/java/com/example/mytodolist/service/UserService.java
  contents/todoListAPI/hj/MyTodoList/src/main/resources/application.yml
  contents/todoListAPI/hj/MyTodoList/src/main/resources/logback-spring.xml
Labels: ✨ New Feature, ♻️ Refactoring

#80 [feat] 5주차 과제 구현
  contents/concepts/week5/Untitled 1.png
  contents/concepts/week5/Untitled 2.png
  contents/concepts/week5/Untitled 3.png
  contents/concepts/week5/Untitled.png
  contents/concepts/week5/스프링 커스텀 예외처리 44e35a1d4b7d4799b1788c00fc4c8367.md
  contents/todoListAPI/ja/TodoProject/build.gradle
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/config/GlobalExceptionHandler.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/config/ex/DuplicatedException.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/config/ex/NotFoundException.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/controller/ClientController.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/controller/TodoController.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/controller/TodoGroupController.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/Client/ClientRequestDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/Client/ClientResponseDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/Todo/TodoRequestDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/Todo/TodoResponseDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/dto/TodoGroup/TodoGroupRequestDto.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/entity/Client.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/entity/Todo.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/entity/TodoGroup.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/repository/TodoRepository.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/service/ClientService.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/service/TodoGroupService.java
  contents/todoListAPI/ja/TodoProject/src/main/java/com/example/TodoProject/service/TodoService.java
Labels: 🧹 Clean Up, ✨ New Feature, ♻️ Refactoring

#82 [Feat] 유효성 검사 및 예외처리 구현
  .idea/misc.xml
  contents/concepts/week4/ch/4주차.md
  contents/todoListAPI/ch/todo/.idea/modules.xml
  contents/todoListAPI/ch/todo/.idea/modules/todo.main.iml
  contents/todoListAPI/ch/todo/.idea/vcs.xml
  contents/todoListAPI/ch/todo/build.gradle
  contents/todoListAPI/ch/todo/src/main/java/com/example/todo/common/GlobalControllerAdvice.java
  contents/todoListAPI/ch/todo/src/main/java/com/example/todo/common/ValidationGroup.java
  contents/todoListAPI/ch/todo/src/main/java/com/example/todo/task/Task.java
  contents/todoListAPI/ch/todo/src/main/java/com/example/todo/task/TaskController.java
  contents/todoListAPI/ch/todo/src/main/java/com/example/todo/task/TaskRepository.java
  contents/todoListAPI/ch/todo/src/main/java/com/example/todo/task/TaskService.java
  contents/todoListAPI/ch/todo/src/main/java/com/example/todo/task/dto/TaskRequestDto.java
  contents/todoListAPI/ch/todo/src/main/java/com/example/todo/task/dto/TaskResponseDto.java
  contents/todoListAPI/ch/todo/src/main/java/com/example/todo/user/User.java
  contents/todoListAPI/ch/todo/src/main/java/com/example/todo/user/UserController.java
  contents/todoListAPI/ch/todo/src/main/java/com/example/todo/user/UserService.java
  contents/todoListAPI/ch/todo/src/main/java/com/example/todo/user/dto/UserRequestDto.java
  contents/todoListAPI/ch/todo/src/main/java/com/example/todo/user/dto/UserResponseDto.java
Labels: ✨ New Feature

#78 [Feat] 예외처리&유효성검사&로깅 구현
  contents/concepts/week5/hs/Logging 91474832ab34442a80753b578b4d8ae1.md
  contents/concepts/week5/hs/Logging 91474832ab34442a80753b578b4d8ae1/Untitled 1.png
  contents/concepts/week5/hs/Logging 91474832ab34442a80753b578b4d8ae1/Untitled 2.png
  contents/concepts/week5/hs/Logging 91474832ab34442a80753b578b4d8ae1/Untitled 3.png
  contents/concepts/week5/hs/Logging 91474832ab34442a80753b578b4d8ae1/Untitled 4.png
  contents/concepts/week5/hs/Logging 91474832ab34442a80753b578b4d8ae1/Untitled 5.png
  contents/concepts/week5/hs/Logging 91474832ab34442a80753b578b4d8ae1/Untitled 6.png
  contents/concepts/week5/hs/Logging 91474832ab34442a80753b578b4d8ae1/Untitled 7.png
  contents/concepts/week5/hs/Logging 91474832ab34442a80753b578b4d8ae1/Untitled 8.png
  contents/concepts/week5/hs/Logging 91474832ab34442a80753b578b4d8ae1/Untitled 9.png
  contents/concepts/week5/hs/Logging 91474832ab34442a80753b578b4d8ae1/Untitled.png
  contents/todoListAPI/hs/toDoList/build.gradle
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/controller/MemberController.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/controller/TaskController.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/domain/Task.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/dto/MemberSaveDto.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/dto/MemberUpdateDto.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/dto/TaskListResponseDto.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/dto/TaskResponseDto.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/dto/TaskSaveDto.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/dto/TaskUpdateDto.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/exception/MyExceptionHandler.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/exception/ex/MyDuplicateException.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/exception/ex/MyErrorCode.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/exception/ex/MyNotFoundException.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/repositoy/MemberRepository.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/service/MemberService.java
  contents/todoListAPI/hs/toDoList/src/main/java/com/study/toDoList/service/TaskService.java
  contents/todoListAPI/hs/toDoList/src/main/resources/application.properties
Labels: ✨ New Feature, ♻️ Refactoring

#77 [Feat,Docs] - 예외처리 및 유효성검사 구현 & 5주차 발표자료
  contents/concepts/week5/sy/image1.png
  contents/concepts/week5/sy/validation.md
  contents/todoListAPI/sy/ToDoList/build.gradle
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Controller/EmotionController.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Controller/ReplyController.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Controller/ToDoController.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Controller/UserController.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/CommonResponseDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/Reply/AddReplyReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/Reply/ChangeReplyReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/Reply/ReadReplyResDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/ToDo/AddToDoReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/ToDo/ReadToDoResDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/ToDo/UpdateToDoReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/User/AddUserReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/User/ChangeUserReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/User/DeleteUserReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/User/ReadUserResDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Exception/CommonExceptionHandler.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Exception/CommondException.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Exception/ExceptionCode.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Service/EmotionService.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Service/ReplyService.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Service/ToDoService.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Service/UserService.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/Emotion.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/Reply.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/ToDo.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/User.java
  contents/todoListAPI/sy/ToDoList/src/main/resources/application.properties
Labels: ✨ New Feature, ♻️ Refactoring

#90 [Docs] - 6주차 발표자료
  contents/concepts/week6/sy/6주차.md
  contents/todoListAPI/sy/ToDoList/.github/workflows/main.yml
  contents/todoListAPI/sy/ToDoList/build.gradle
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Config/SwaggerConfig.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Config/Workaround.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Controller/EmotionController.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Controller/ReplyController.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Controller/ToDoController.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Controller/UserController.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/ToDo/AddToDoReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/ToDo/ReadToDoResDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/User/AddUserReqDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/DTO/User/ReadUserResDTO.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Exception/CommonExceptionHandler.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Exception/ExceptionCode.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Repository/UserRepository.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Service/ReplyService.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/Service/ToDoService.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/BaseEntity.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/Emotion.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/Reply.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/ToDo.java
  contents/todoListAPI/sy/ToDoList/src/main/java/com/example/todolist/domain/User.java
  contents/todoListAPI/sy/ToDoList/src/main/resources/application.properties
Labels: 📘 Documentation
